version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=password
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=diamond_calculation_system
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - ./database:/var/lib/mysql